name: spell_corrector
publish_to: none
repository: https://github.com/gordianknotC/spell_corrector.git
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: gordianknot <email@example.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"


dev_dependencies:
  test: ^1.0.0
